import Head from 'next/head';

import { useState } from 'react';
import web3 from '../Blockend/web3';
import Homepage from '../Component/HomeOld/Homepage';

export default function Home() {

  // web3.eth.getAccounts().then(console.log);

  const [account, setAccount] = useState("");
  return (
    <div >
      <Head>
        <title>Wallet Resolver</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/eth.jpg" />
      </Head>


      <Homepage />


    </div>
  )
}
